export const ADD_STAFFS = 'ADD_STAFFS';
export const STAFFS_LOADING = 'STAFFS_LOADING';
export const STAFFS_FAILED = 'STAFFS_FAILED';
export const STAFFS_DELETE = 'STAFFS_DELETE';
export const STAFFS_UPDATE = 'STAFFS_UPDATE';


export const DEPARTMENTS_LOADING = 'DEPARTMENTS_LOADING';
export const DEPARTMENTS_FAILED = 'DEPARTMENTS_FAILED';
export const ADD_DEPARTMENTS ='ADD_DEPARTMENTS';
